FROM node:20-alpine AS builder

WORKDIR /app

COPY admin-portal/package*.json ./
RUN npm ci

COPY admin-portal/ .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/.output ./.output

EXPOSE 3003

ENV PORT=3003

CMD ["node", ".output/server/index.mjs"]
