FROM node:20-alpine AS builder

WORKDIR /app

COPY otex/package*.json ./
RUN npm install

COPY otex/ .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/.output ./.output

EXPOSE 3002

ENV PORT=3002

CMD ["node", ".output/server/index.mjs"]
