FROM node:20-alpine AS builder

WORKDIR /app

COPY publisher-portal/package*.json ./
RUN npm ci

COPY publisher-portal/ .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/.output ./.output

EXPOSE 3001

ENV PORT=3001

CMD ["node", ".output/server/index.mjs"]
