FROM node:20-alpine AS builder

WORKDIR /app

COPY advertiser-portal/package*.json ./
RUN npm install

COPY advertiser-portal/ .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY --from=builder /app/.output ./.output

EXPOSE 3000

ENV PORT=3000

CMD ["node", ".output/server/index.mjs"]
