/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AppZonesRouteImport } from './routes/_app.zones'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppStatsRouteImport } from './routes/_app.stats'
import { Route as AppSitesRouteImport } from './routes/_app.sites'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppPayoutsRouteImport } from './routes/_app.payouts'
import { Route as AppAdcodeRouteImport } from './routes/_app.adcode'
import { Route as AppZonesZoneIdRouteImport } from './routes/_app.zones.$zoneId'
import { Route as AppSitesSiteIdRouteImport } from './routes/_app.sites.$siteId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppZonesRoute = AppZonesRouteImport.update({
  id: '/zones',
  path: '/zones',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppSitesRoute = AppSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppPayoutsRoute = AppPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AppRoute,
} as any)
const AppAdcodeRoute = AppAdcodeRouteImport.update({
  id: '/adcode',
  path: '/adcode',
  getParentRoute: () => AppRoute,
} as any)
const AppZonesZoneIdRoute = AppZonesZoneIdRouteImport.update({
  id: '/$zoneId',
  path: '/$zoneId',
  getParentRoute: () => AppZonesRoute,
} as any)
const AppSitesSiteIdRoute = AppSitesSiteIdRouteImport.update({
  id: '/$siteId',
  path: '/$siteId',
  getParentRoute: () => AppSitesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/adcode': typeof AppAdcodeRoute
  '/payouts': typeof AppPayoutsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/sites': typeof AppSitesRouteWithChildren
  '/stats': typeof AppStatsRoute
  '/support': typeof AppSupportRoute
  '/zones': typeof AppZonesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/sites/$siteId': typeof AppSitesSiteIdRoute
  '/zones/$zoneId': typeof AppZonesZoneIdRoute
}
export interface FileRoutesByTo {
  '/adcode': typeof AppAdcodeRoute
  '/payouts': typeof AppPayoutsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/sites': typeof AppSitesRouteWithChildren
  '/stats': typeof AppStatsRoute
  '/support': typeof AppSupportRoute
  '/zones': typeof AppZonesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/': typeof AppIndexRoute
  '/sites/$siteId': typeof AppSitesSiteIdRoute
  '/zones/$zoneId': typeof AppZonesZoneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/adcode': typeof AppAdcodeRoute
  '/_app/payouts': typeof AppPayoutsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sites': typeof AppSitesRouteWithChildren
  '/_app/stats': typeof AppStatsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/zones': typeof AppZonesRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/sites/$siteId': typeof AppSitesSiteIdRoute
  '/_app/zones/$zoneId': typeof AppZonesZoneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adcode'
    | '/payouts'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/stats'
    | '/support'
    | '/zones'
    | '/auth/login'
    | '/auth/register'
    | '/sites/$siteId'
    | '/zones/$zoneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/adcode'
    | '/payouts'
    | '/reports'
    | '/settings'
    | '/sites'
    | '/stats'
    | '/support'
    | '/zones'
    | '/auth/login'
    | '/auth/register'
    | '/'
    | '/sites/$siteId'
    | '/zones/$zoneId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/adcode'
    | '/_app/payouts'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/sites'
    | '/_app/stats'
    | '/_app/support'
    | '/_app/zones'
    | '/auth/login'
    | '/auth/register'
    | '/_app/'
    | '/_app/sites/$siteId'
    | '/_app/zones/$zoneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/zones': {
      id: '/_app/zones'
      path: '/zones'
      fullPath: '/zones'
      preLoaderRoute: typeof AppZonesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sites': {
      id: '/_app/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AppSitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payouts': {
      id: '/_app/payouts'
      path: '/payouts'
      fullPath: '/payouts'
      preLoaderRoute: typeof AppPayoutsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/adcode': {
      id: '/_app/adcode'
      path: '/adcode'
      fullPath: '/adcode'
      preLoaderRoute: typeof AppAdcodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/zones/$zoneId': {
      id: '/_app/zones/$zoneId'
      path: '/$zoneId'
      fullPath: '/zones/$zoneId'
      preLoaderRoute: typeof AppZonesZoneIdRouteImport
      parentRoute: typeof AppZonesRoute
    }
    '/_app/sites/$siteId': {
      id: '/_app/sites/$siteId'
      path: '/$siteId'
      fullPath: '/sites/$siteId'
      preLoaderRoute: typeof AppSitesSiteIdRouteImport
      parentRoute: typeof AppSitesRoute
    }
  }
}

interface AppSitesRouteChildren {
  AppSitesSiteIdRoute: typeof AppSitesSiteIdRoute
}

const AppSitesRouteChildren: AppSitesRouteChildren = {
  AppSitesSiteIdRoute: AppSitesSiteIdRoute,
}

const AppSitesRouteWithChildren = AppSitesRoute._addFileChildren(
  AppSitesRouteChildren,
)

interface AppZonesRouteChildren {
  AppZonesZoneIdRoute: typeof AppZonesZoneIdRoute
}

const AppZonesRouteChildren: AppZonesRouteChildren = {
  AppZonesZoneIdRoute: AppZonesZoneIdRoute,
}

const AppZonesRouteWithChildren = AppZonesRoute._addFileChildren(
  AppZonesRouteChildren,
)

interface AppRouteChildren {
  AppAdcodeRoute: typeof AppAdcodeRoute
  AppPayoutsRoute: typeof AppPayoutsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSitesRoute: typeof AppSitesRouteWithChildren
  AppStatsRoute: typeof AppStatsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppZonesRoute: typeof AppZonesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdcodeRoute: AppAdcodeRoute,
  AppPayoutsRoute: AppPayoutsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSitesRoute: AppSitesRouteWithChildren,
  AppStatsRoute: AppStatsRoute,
  AppSupportRoute: AppSupportRoute,
  AppZonesRoute: AppZonesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
