/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AppWalletRouteImport } from './routes/_app.wallet'
import { Route as AppTargetingRouteImport } from './routes/_app.targeting'
import { Route as AppSupportRouteImport } from './routes/_app.support'
import { Route as AppStatsRouteImport } from './routes/_app.stats'
import { Route as AppRtbRouteImport } from './routes/_app.rtb'
import { Route as AppKycRouteImport } from './routes/_app.kyc'
import { Route as AppCreativesRouteImport } from './routes/_app.creatives'
import { Route as AppComplianceRouteImport } from './routes/_app.compliance'
import { Route as AppCdnRouteImport } from './routes/_app.cdn'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppCampaignsIndexRouteImport } from './routes/_app.campaigns.index'
import { Route as AppCampaignsNewRouteImport } from './routes/_app.campaigns.new'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AppRoute,
} as any)
const AppTargetingRoute = AppTargetingRouteImport.update({
  id: '/targeting',
  path: '/targeting',
  getParentRoute: () => AppRoute,
} as any)
const AppSupportRoute = AppSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AppRoute,
} as any)
const AppStatsRoute = AppStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => AppRoute,
} as any)
const AppRtbRoute = AppRtbRouteImport.update({
  id: '/rtb',
  path: '/rtb',
  getParentRoute: () => AppRoute,
} as any)
const AppKycRoute = AppKycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => AppRoute,
} as any)
const AppCreativesRoute = AppCreativesRouteImport.update({
  id: '/creatives',
  path: '/creatives',
  getParentRoute: () => AppRoute,
} as any)
const AppComplianceRoute = AppComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AppRoute,
} as any)
const AppCdnRoute = AppCdnRouteImport.update({
  id: '/cdn',
  path: '/cdn',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIndexRoute = AppCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppCampaignsRoute,
} as any)
const AppCampaignsNewRoute = AppCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppCampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/cdn': typeof AppCdnRoute
  '/compliance': typeof AppComplianceRoute
  '/creatives': typeof AppCreativesRoute
  '/kyc': typeof AppKycRoute
  '/rtb': typeof AppRtbRoute
  '/stats': typeof AppStatsRoute
  '/support': typeof AppSupportRoute
  '/targeting': typeof AppTargetingRoute
  '/wallet': typeof AppWalletRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/campaigns/': typeof AppCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/cdn': typeof AppCdnRoute
  '/compliance': typeof AppComplianceRoute
  '/creatives': typeof AppCreativesRoute
  '/kyc': typeof AppKycRoute
  '/rtb': typeof AppRtbRoute
  '/stats': typeof AppStatsRoute
  '/support': typeof AppSupportRoute
  '/targeting': typeof AppTargetingRoute
  '/wallet': typeof AppWalletRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/': typeof AppIndexRoute
  '/campaigns/new': typeof AppCampaignsNewRoute
  '/campaigns': typeof AppCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_app/cdn': typeof AppCdnRoute
  '/_app/compliance': typeof AppComplianceRoute
  '/_app/creatives': typeof AppCreativesRoute
  '/_app/kyc': typeof AppKycRoute
  '/_app/rtb': typeof AppRtbRoute
  '/_app/stats': typeof AppStatsRoute
  '/_app/support': typeof AppSupportRoute
  '/_app/targeting': typeof AppTargetingRoute
  '/_app/wallet': typeof AppWalletRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/_app/': typeof AppIndexRoute
  '/_app/campaigns/new': typeof AppCampaignsNewRoute
  '/_app/campaigns/': typeof AppCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns'
    | '/cdn'
    | '/compliance'
    | '/creatives'
    | '/kyc'
    | '/rtb'
    | '/stats'
    | '/support'
    | '/targeting'
    | '/wallet'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/campaigns/new'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cdn'
    | '/compliance'
    | '/creatives'
    | '/kyc'
    | '/rtb'
    | '/stats'
    | '/support'
    | '/targeting'
    | '/wallet'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/'
    | '/campaigns/new'
    | '/campaigns'
  id:
    | '__root__'
    | '/_app'
    | '/_app/campaigns'
    | '/_app/cdn'
    | '/_app/compliance'
    | '/_app/creatives'
    | '/_app/kyc'
    | '/_app/rtb'
    | '/_app/stats'
    | '/_app/support'
    | '/_app/targeting'
    | '/_app/wallet'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/_app/'
    | '/_app/campaigns/new'
    | '/_app/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/wallet': {
      id: '/_app/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/targeting': {
      id: '/_app/targeting'
      path: '/targeting'
      fullPath: '/targeting'
      preLoaderRoute: typeof AppTargetingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/support': {
      id: '/_app/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AppSupportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stats': {
      id: '/_app/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof AppStatsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rtb': {
      id: '/_app/rtb'
      path: '/rtb'
      fullPath: '/rtb'
      preLoaderRoute: typeof AppRtbRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kyc': {
      id: '/_app/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof AppKycRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/creatives': {
      id: '/_app/creatives'
      path: '/creatives'
      fullPath: '/creatives'
      preLoaderRoute: typeof AppCreativesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/compliance': {
      id: '/_app/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AppComplianceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cdn': {
      id: '/_app/cdn'
      path: '/cdn'
      fullPath: '/cdn'
      preLoaderRoute: typeof AppCdnRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/': {
      id: '/_app/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof AppCampaignsIndexRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
    '/_app/campaigns/new': {
      id: '/_app/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof AppCampaignsNewRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsNewRoute: typeof AppCampaignsNewRoute
  AppCampaignsIndexRoute: typeof AppCampaignsIndexRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsNewRoute: AppCampaignsNewRoute,
  AppCampaignsIndexRoute: AppCampaignsIndexRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppRouteChildren {
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppCdnRoute: typeof AppCdnRoute
  AppComplianceRoute: typeof AppComplianceRoute
  AppCreativesRoute: typeof AppCreativesRoute
  AppKycRoute: typeof AppKycRoute
  AppRtbRoute: typeof AppRtbRoute
  AppStatsRoute: typeof AppStatsRoute
  AppSupportRoute: typeof AppSupportRoute
  AppTargetingRoute: typeof AppTargetingRoute
  AppWalletRoute: typeof AppWalletRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppCdnRoute: AppCdnRoute,
  AppComplianceRoute: AppComplianceRoute,
  AppCreativesRoute: AppCreativesRoute,
  AppKycRoute: AppKycRoute,
  AppRtbRoute: AppRtbRoute,
  AppStatsRoute: AppStatsRoute,
  AppSupportRoute: AppSupportRoute,
  AppTargetingRoute: AppTargetingRoute,
  AppWalletRoute: AppWalletRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
